Improve decision process for choosing stdeb version
And here's for a very peculiar bug fix... I was trying to convert
PyXML 0.8.4 to a Debian package and the setup.py script kept failing
with "error: invalid command 'debianize'". After much digging:

 * py2deb runs "python setup.py --command-packages=stdeb.command debianize"
   which implies that "from stdeb.command import debianize" is run.

 * "import stdeb" actually imports the module bundled with py2deb (which
   automatically pick the right version of stdeb for the current platform)
   and this module imported py2deb -> pip-accel -> pip -> html5lib
   (bundled with pip) which then blows up with:

     >>> import xml.etree.ElementTree as default_etree
     ImportError: No module named etree.ElementTree

 * Turns out PyXML 0.8.4 indeed contains an "xml" module... This all
   happens because Python implicitly imports from the current working
   directory before the rest of the entries in sys.path and PyXML
   actually depends on this; take a look at the setup.py script.

Lesson learned: I guess it's wise to restrict our bundled
fake stdeb module to standard library module imports :-).